/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_bdr_eidclient_EIdSession */

#ifndef _Included_de_bdr_eidclient_EIdSession
#define _Included_de_bdr_eidclient_EIdSession
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_bdr_eidclient_EIdSession
 * Method:    nativePipeSTDOUTToLogcat
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_de_bdr_eidclient_EIdSession_pipeStdOut
  (JNIEnv *, jobject);

/*
 * Class:     de_bdr_eidclient_EIdSession
 * Method:    performEAC
 * Signature: (Lde/bdr/eidclient/reader/Reader;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_de_bdr_eidclient_EIdSession_performEAC
  (JNIEnv *, jobject, jobject, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
