language: c

env:
  global:
    - PREFIX=$HOME/target
    - INSECURE=true

compiler:
  - clang
  - gcc

install:
  - make cryptopp libexpat openssl libcurl asn1c PREFIX=$PREFIX INSECURE=$INSECURE

script:
  - make eIDClient PREFIX=$PREFIX INSECURE=$INSECURE

cache:
  directories:
    - $HOME/target
